name: python-helloworld

on:
  push:
    branches: [main]

jobs:
  build:
    steps:

      matrix: 
      - platform: [linux/amd64, linux/arm64]
      - runs-on: ${{ matrix.platform }}
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: python app.py

    - name: Login to Docker Hub
    - uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: user/app:latest



