name: python-helloworld

on: [push]

tags: latest

jobs:
  matrix: 
    platform: [linux/amd64, linux/arm64]

  runs-on: ${{ matrix.platform }}

  steps:
    name: Login to Docker Hub
    uses: docker/login-action@v1
    with: 
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

    uses: docker/build-push-action@v2



